
package com.example;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FacilityService", targetNamespace = "http://example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FacilityService {


    /**
     * 
     * @return
     *     returns com.example.Facility
     */
    @WebMethod
    @WebResult(name = "myFacility", targetNamespace = "")
    @RequestWrapper(localName = "getFacility", targetNamespace = "http://example.com/", className = "com.example.GetFacility")
    @ResponseWrapper(localName = "getFacilityResponse", targetNamespace = "http://example.com/", className = "com.example.GetFacilityResponse")
    @Action(input = "http://example.com/FacilityService/getFacilityRequest", output = "http://example.com/FacilityService/getFacilityResponse")
    public Facility getFacility();

}
