
package com.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FacilitySOAPService", targetNamespace = "http://example.com/", wsdlLocation = "http://localhost:8090/two?wsdl")
public class FacilitySOAPService
    extends Service
{

    private final static URL FACILITYSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FACILITYSOAPSERVICE_EXCEPTION;
    private final static QName FACILITYSOAPSERVICE_QNAME = new QName("http://example.com/", "FacilitySOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/two?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACILITYSOAPSERVICE_WSDL_LOCATION = url;
        FACILITYSOAPSERVICE_EXCEPTION = e;
    }

    public FacilitySOAPService() {
        super(__getWsdlLocation(), FACILITYSOAPSERVICE_QNAME);
    }

    public FacilitySOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACILITYSOAPSERVICE_QNAME, features);
    }

    public FacilitySOAPService(URL wsdlLocation) {
        super(wsdlLocation, FACILITYSOAPSERVICE_QNAME);
    }

    public FacilitySOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACILITYSOAPSERVICE_QNAME, features);
    }

    public FacilitySOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacilitySOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FacilityService
     */
    @WebEndpoint(name = "FacilityServicePort")
    public FacilityService getFacilityServicePort() {
        return super.getPort(new QName("http://example.com/", "FacilityServicePort"), FacilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacilityService
     */
    @WebEndpoint(name = "FacilityServicePort")
    public FacilityService getFacilityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/", "FacilityServicePort"), FacilityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACILITYSOAPSERVICE_EXCEPTION!= null) {
            throw FACILITYSOAPSERVICE_EXCEPTION;
        }
        return FACILITYSOAPSERVICE_WSDL_LOCATION;
    }

}
